### ISSUE TITLE
[FEAT] 유저의 위치 저장 로직 

### ISSUE THREAD

**Issue by GoodDonkey** [Biom-side-project/biom-backend#10]
**Feature Description**  
프론트에서 보내주는 위치 저장 로직을 만든다.

**Todos**  
- [x] 법정동 코드를 미리 저장해둔다.
- [x] 유저의 위치 (x, y 또는 지역정보) 를 활용 및 저장.
- [x] 이 위치에 따라 비옴 확률 계산 등 할 수 있는 기반 마련
