### ISSUE TITLE
[FEAT] 개발 환경 세팅

### ISSUE THREAD

**Issue by GoodDonkey** [Biom-side-project/biom-backend#2]
# 개발 환경 세팅

## subtasks

- [x]  gradle module 세팅
- [x]  /health 응답 엔드포인트 생성
- [x]  test / local / dev / prod 환경 나누기
- [x]  value 주입 세팅하기
- [x]  Dockerfile
- [x]  CI/CD

## 프로젝트 세팅

java 11

gradle

lombok 

spring mvc

spring security

spring validation

spring jpa

jwt 

mysql

h2
