### ISSUE TITLE
[FEAT] 유저 정보를 가져오도록 하는 기능.

### ISSUE THREAD

**Issue by GoodDonkey** [Biom-side-project/biom-backend#22]
**Feature Description**  
유저 정보를 가져올 수 있게 한다.
기본적으로 구글에서 받는 정보는 
- 본명, 
- 이메일, 
- 프로필 사진uri 
이고, 서버에서 추가적으로 Role, 소셜 로그인 타입을 저장한다.(보내지는 말자)

커뮤니티 기능이 있으니, 추가적으로 닉네임이 있어야 한다.

**Todos**  
- [x] 구글로부터 받는 기본정보를 반환한다.
- [x] 닉네임이 없으면 무작위로 회원가입 시 하나 만들어 둔다. 
- [x] 위의 유저정보를 프론트에서 가져올 수 있도록 구현.
- [x] 닉네임을 수정할 수 있는 엔드포인트를 만든다.
