### ISSUE TITLE
[FEAT] 커뮤니티 기능

### ISSUE THREAD

**Issue by GoodDonkey** [Biom-side-project/biom-backend#29]
**Description**  
커뮤니티 기능 개발

**Todos**  
- [x] 지역에 따라 댓글을 남길 수 있다.
- [x] 지역에 따른 댓글들을 불러올 수 있다.
- [ ] 댓글에 좋아요를 누를 수 있다.
