### ISSUE TITLE
[FEAT] 비옴 비율 계산 개선하기

### ISSUE THREAD

**Issue by GoodDonkey** [Biom-side-project/biom-backend#39]
**Description**  
비옴 비율을 계산하는 방법을 개선한다.

**Todos**  
- [ ] 반올림하여 반환하기
- [ ] 계산 방식을 쿼리하는 것에서 캐싱하는 방식으로 개선하기
- [ ] 업데이트 간격을 유동적으로 조절할 수 있도록 개발.
- [ ] 비옴 / 안옴 입력이 없을 때 어떻게 할지 결정하기
